### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by thornsu** [KinglittleQ/SuperPoint_SLAM#1]
Hello，Thanks for your code. When I build the project,  there are some error:
[  6%] Building CXX object CMakeFiles/ORB_SLAM2.dir/src/Optimizer.cc.o
In file included from /usr/include/eigen3/Eigen/Sparse:28:0,
                 from /home/ustc406/slam/SuperPoint_SLAM-master/Thirdparty/g2o/g2o/solvers/linear_solver_eigen.h:30,
                 from /home/ustc406/slam/SuperPoint_SLAM-master/src/Optimizer.cc:25:
/usr/include/eigen3/Eigen/SparseCholesky:34:2: error: #error The SparseCholesky module has nothing to offer in MPL2 only mode
 #error The SparseCholesky module has nothing to offer in MPL2 only mode
  ^
In file included from /usr/include/eigen3/Eigen/SparseCholesky:37:0,
                 from /usr/include/eigen3/Eigen/Sparse:28,
                 from /home/ustc406/slam/SuperPoint_SLAM-master/Thirdparty/g2o/g2o/solvers/linear_solver_eigen.h:30,
                 from /home/ustc406/slam/SuperPoint_SLAM-master/src/Optimizer.cc:25:
/usr/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h:268:72: error: ‘AMDOrdering’ does not name a type
......
I succeed build DBoW3 and g2o, and I never get the same problem in other slam_system like ORB_SLAM2, look forward to your reply.

**Comment by KinglittleQ** [comment]
You can solve it in two methods. 

1. The first is to comment out `#define EIGEN_MPL2_ONLY` in the libtorch headers. You can search ` EIGEN_MPL2_ONLY` in the compiled libtorch library and comment it out.

2. The second way is to add follwing statement in the source code where caused the error:
```
#ifdef EIGEN_MPL2_ONLY
#undef EIGEN_MPL2_ONLY
#endif
```
In your case, you can add the above code into `Optimizer.h`.

**Comment by KinglittleQ** [comment]
This is not a released version so I didn't build it again starting from scratch. I will upload a more complete version including DBoW3 library and vocabulary in the future.
