### ISSUE TITLE
[SuperPoint_SLAM] make: *** [all] Error 2

### ISSUE THREAD

**Issue by Moonkisscy** [KinglittleQ/SuperPoint_SLAM#10]
Thank for your good work.
I install pytorch by anaconda. Then  I meet some problems. Do you know how to solve that? Thakns.

`:MIN_COMMON_WORDS’ defined but not used [-Wunused-variable]
 static int MIN_COMMON_WORDS = 5;
            ^
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/SuerPoint_SLAM.dir/all' failed
make[1]: *** [CMakeFiles/SuerPoint_SLAM.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by KinglittleQ** [comment]
You should install LibTorch rather than PyTorch. LibTorch is the C++ version of PyTorch.

**Comment by Moonkisscy** [comment]
> You should install LibTorch rather than PyTorch. LibTorch is the C++ version of PyTorch.

Yes. I installed LibTorch  according the "Readme", but it always failed.

**Comment by KinglittleQ** [comment]
Please show me the full output log.

**Comment by Moonkisscy** [comment]
> Please show me the full output log.

Thank you. I'm downloading, it always takes a long time to download, and then the download fails.

**Comment by KinglittleQ** [comment]
You can try to download the source code and submodules in `.zip` format manually.

https://github.com/pytorch/pytorch

**Comment by Moonkisscy** [comment]
Yes.I tried it before，but it can not work. It remined some files must be  download by git.

**Comment by Moonkisscy** [comment]
> You can try to download the source code and submodules in `.zip` format manually.
> 
> https://github.com/pytorch/pytorch

Thank you.
`wget https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip
unzip libtorch-shared-with-deps-latest.zip`
I download the  LibTorch ZIP archive via the link above, and run the example success.
However, it still has some problems when build superpointslam.
![image](https://user-images.githubusercontent.com/11571329/70492435-68997b00-1b3f-11ea-8542-b1c1f0103b74.png)
`/home/**/myslam/SuperPoint_SLAM/Thirdparty/libtorch/include/c10/util/C++17.h:20:2: error: #error You need C++14 to compile PyTorch
 #error You need C++14 to compile PyTorch
`

**Comment by KinglittleQ** [comment]
Using the prebuilt version would cause some problems. It is better to build it from scratch.
