### ISSUE TITLE
找不到eigen3

### ISSUE THREAD

**Issue by yaolinggezhu** [KinglittleQ/SuperPoint_SLAM#13]
你好，我运行./build.sh时老是报错：
Could not find a configuration file for package "Eigen3" that is compatible
  with requested version "3.1.0".

  The following configuration files were considered but not accepted:

    /usr/lib/cmake/eigen3/Eigen3Config.cmake, version: unknown
我的eigen版本是3.2.92，是使用libeigen3-dev安装的

**Comment by yaolinggezhu** [comment]
> 
> 
> 你好，我运行./build.sh时老是报错：
> Could not find a configuration file for package "Eigen3" that is compatible
> with requested version "3.1.0".
> 
> The following configuration files were considered but not accepted:
> 
> ```
> /usr/lib/cmake/eigen3/Eigen3Config.cmake, version: unknown
> ```
> 
> 我的eigen版本是3.2.92，是使用libeigen3-dev安装的

希望能得到解答，谢谢

**Comment by KinglittleQ** [comment]
Set Eigen3 library directory manually [here](https://github.com/KinglittleQ/SuperPoint_SLAM/blob/0e850e4b6c86f04cf9f003b3572ca1e4463353a9/CMakeLists.txt#L15).

``` cmake
set(Eigen3_DIR "/your/eigen3/directory/")
```
