### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by Y-pandaman** [KinglittleQ/SuperPoint_SLAM#16]
想请教一下，我装了libtorch1.3.0，是用​GitHub上的源码编译的，superpoint_slam的代码clone下来之后运行的时候图片显示一卡一卡的，感觉就像是用CPU跑的，没有用上GPU，查了一下GPU的状态，就是没使用GPU，请问怎么设置，可以用GPU跑呢？希望能够解答一下，谢谢？我用nvcc -V查看的cuda版本是10.0.130，用nvidia-smi查看cuda版本是10.2

**Comment by KinglittleQ** [comment]
你看一下SuperPoint.cc的源码，可以在里面启用cuda

**Comment by Y-pandaman** [comment]
> 你看一下SuperPoint.cc的源码，可以在里面启用cuda

谢谢回复，我看了一下superpoint.cc的源码，里面涉及到cuda只有两个地方，一个是void SPDetector::detect(cv::Mat &img, bool cuda)，另一个是cv::Mat SPdetect(std::shared_ptr<SuperPoint> model, cv::Mat img, std::vector<cv::KeyPoint> &keypoints, double threshold, bool nms, bool cuda)，其中SPdetect函数没有被调用，在SPextractor.cc文件中被注释掉了，而SPdetector函数中的cuda参数默认是设置成false的，我将它改成true之后，运行程序就会报错terminate called after throwing an instance of 'c10::Error'  what():  grid_sampler(): expected input and grid to be on same device, but input is on cuda:0 and grid is on cpu。另外在superpoint.cc文件中的void SPDetector::computeDescriptors(const  std::vector<cv::KeyPoint> &keypoints, cv::Mat &descriptors)函数里，有一处desc = desc.to(torch::kCPU); 我将其改成desc = desc.to(torch::kCUDA); 也不行，直接崩掉。不知道我改的地方对不对，希望还能得到你的回复，谢谢~

**Comment by Y-pandaman** [comment]
谢谢回复，我看了一下superpoint.cc的源码，里面涉及到cuda只有两个地方，一个是void SPDetector::detect(cv::Mat &img, bool cuda)，另一个是cv::Mat SPdetect(std::shared_ptr model, cv::Mat img, std::vectorcv::KeyPoint &keypoints, double threshold, bool nms, bool cuda)，其中SPdetect函数没有被调用，在SPextractor.cc文件中被注释掉了，而SPdetector函数中的cuda参数默认是设置成false的，我将它改成true之后，运行程序就会报错terminate called after throwing an instance of 'c10::Error' what(): grid_sampler(): expected input and grid to be on same device, but input is on cuda:0 and grid is on cpu。另外在superpoint.cc文件中的void SPDetector::computeDescriptors(const std::vectorcv::KeyPoint &keypoints, cv::Mat &descriptors)函数里，有一处desc = desc.to(torch::kCPU); 我将其改成desc = desc.to(torch::kCUDA); 也不行，直接崩掉。不知道我改的地方对不对，希望还能得到你的回复，谢谢~

**Comment by KinglittleQ** [comment]
你看一下这个[issue](https://github.com/KinglittleQ/SuperPoint_SLAM/issues/6#issuecomment-572364854)，参考一下他的改法

**Comment by Y-pandaman** [comment]
谢谢大佬，问题已经解决了，是在`SPDetector::computeDescriptors(const std::vector<cv::KeyPoint> &keypoints, cv::Mat &descriptors)`函数中的` auto desc = torch::grid_sampler(mDesc, grid, 0, 0); `前面加上`grid = grid.to(torch::kCUDA);`

**Comment by liubamboo** [comment]
@KinglittleQ 请问你使用的cuda版本是多少呢？

**Comment by liubamboo** [comment]
@Y-pandaman 你好，请问你可以用gpu运行了吗，我按照你的方法在SPDetector::computeDescriptors(const std::vector<cv::KeyPoint> &keypoints, cv::Mat &descriptors)函数中的auto desc = torch::grid_sampler(mDesc, grid, 0, 0);前面加上grid = grid.to(torch::kCUDA);
但是运行出现了如下问题：
OpenCV Error: Assertion failed (!src[i].empty() && src[i].dims <= 2 && src[i].cols == src[0].cols && src[i].type() == src[0].type()) in vconcat, file /home/n609/install/opencv-2.4.11/modules/core/src/matrix.cpp, line 1794
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/n609/install/opencv-2.4.11/modules/core/src/matrix.cpp:1794: error: (-215) !src[i].empty() && src[i].dims <= 2 && src[i].cols == src[0].cols && src[i].type() == src[0].type() in function vconcat

似乎是更改之后维度不统一了，请问你有遇到过或者有解决办法吗？

**Comment by liubamboo** [comment]
解决了，谢谢，最后是
（1）SPextractor.cc中更改detector.detect(mvImagePyramid[level], true); //use gpu
（2）在SPDetector::computeDescriptors(const std::vectorcv::KeyPoint &keypoints, cv::Mat &descriptors)函数中的auto desc = torch::grid_sampler(mDesc, grid, 0, 0);前面加上grid = grid.to(torch::kCUDA);
（3）https://github.com/KinglittleQ/SuperPoint_SLAM/blob/5d4dff48a0ea7e277fa83a077a139a689331825b/src/SuperPoint.cc#L133在这里前面也加上grid = grid.to(torch::kCUDA);

**Comment by Y-pandaman** [comment]
有几个序列一直都跑不了，都会报这个错，不知道你是不是每个序列都能跑




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KinglittleQ/SuperPoint_SLAM"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月5日(星期六) 晚上7:02
收件人:&nbsp;"KinglittleQ/SuperPoint_SLAM"<SuperPoint_SLAM@noreply.github.com&gt;;
抄送:&nbsp;"妖灵阁主"<2575249103@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [KinglittleQ/SuperPoint_SLAM] 运行问题 (#16)





 
@Y-pandaman 你好，请问你可以用gpu运行了吗，我按照你的方法在SPDetector::computeDescriptors(const std::vectorcv::KeyPoint &amp;keypoints, cv::Mat &amp;descriptors)函数中的auto desc = torch::grid_sampler(mDesc, grid, 0, 0);前面加上grid = grid.to(torch::kCUDA);
 但是运行出现了如下问题：
 OpenCV Error: Assertion failed (!src[i].empty() &amp;&amp; src[i].dims <= 2 &amp;&amp; src[i].cols == src[0].cols &amp;&amp; src[i].type() == src[0].type()) in vconcat, file /home/n609/install/opencv-2.4.11/modules/core/src/matrix.cpp, line 1794
 terminate called after throwing an instance of 'cv::Exception'
 what():  /home/n609/install/opencv-2.4.11/modules/core/src/matrix.cpp:1794: error: (-215) !src[i].empty() &amp;&amp; src[i].dims <= 2 &amp;&amp; src[i].cols == src[0].cols &amp;&amp; src[i].type() == src[0].type() in function vconcat
 
似乎是更改之后维度不统一了，请问你有遇到过或者有解决办法吗？
