### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by cumtchenchang** [KinglittleQ/SuperPoint_SLAM#2]
Thank for your good work, I encounter this error when build this code.
 79%] Built target SuerPoint_SLAM
[ 82%] Linking CXX executable ../Examples/Monocular/mono_euroc
../lib/libSuerPoint_SLAM.so: undefined reference to `pangolin::Split(std::string const&, char)'
../lib/libSuerPoint_SLAM.so: undefined reference to `pangolin::CreatePanel(std::string const&)'
../lib/libSuerPoint_SLAM.so: undefined reference to `DBoW3::Vocabulary::load(std::string const&)'
../lib/libSuerPoint_SLAM.so: undefined reference to `pangolin::BindToContext(std::string)'
../lib/libSuerPoint_SLAM.so: undefined reference to `pangolin::CreateWindowAndBind(std::string, int, int, pangolin::Params const&)'
collect2: error: ld returned 1 exit status
CMakeFiles/mono_euroc.dir/build.make:165: recipe for target '../Examples/Monocular/mono_euroc' failed
make[2]: *** [../Examples/Monocular/mono_euroc] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mono_euroc.dir/all' failed
make[1]: *** [CMakeFiles/mono_euroc.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
However, I build ORB-SLAM2 successfully. Thank you.

**Comment by KinglittleQ** [comment]
@cumtchenchang Did you use the prebuilt version of libtorch? Please build it from scratch following the guide in README.

**Comment by cumtchenchang** [comment]
我按照这个步骤操作
git clone --recursive -b v1.0.1 https://github.com/pytorch/pytorch
cd pytorch && mkdir build && cd build
python ../tools/build_libtorch.py
在python ../tools/build_libtorch.py环节出现这个问题：
-- Using third party subdirectory Eigen.
-- Found PythonLibs: python3.7m
-- System pybind11 found
-- pybind11 include dirs: /usr/local/include;/home/SENSETIME/chenchang1/miniconda3/include/python3.7m
-- MPI support found
-- MPI compile flags: 
-- MPI include path: /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include/usr/lib/openmpi/include/usr/lib/openmpi/include/openmpi
-- MPI LINK flags path:  -Wl,-rpath  -Wl,/usr/lib/openmpi/lib  -Wl,--enable-new-dtags
-- MPI libraries: /usr/lib/openmpi/lib/libmpi_cxx.so/usr/lib/openmpi/lib/libmpi.so
CMake Warning at cmake/Dependencies.cmake:619 (message):
  OpenMPI found, but it is not built with CUDA support.
Call Stack (most recent call first):
  CMakeLists.txt:201 (include)


-- Caffe2: CUDA detected: 9.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 9.0
-- Could NOT find CUDNN (missing:  CUDNN_INCLUDE_DIR CUDNN_LIBRARY) 
CMake Warning at cmake/public/cuda.cmake:110 (message):
  Caffe2: Cannot find cuDNN library.  Turning the option off
Call Stack (most recent call first):
  cmake/Dependencies.cmake:656 (include)
  CMakeLists.txt:201 (include)


CMake Error at cmake/public/cuda.cmake:330 (message):
  CUDA 9.0 is not compatible with std::tuple from GCC version >= 6.  Please
  upgrade to CUDA 9.2 or use the following option to use another version (for
  example):

    -DCUDA_HOST_COMPILER=/usr/bin/gcc-5

Call Stack (most recent call first):
  cmake/Dependencies.cmake:656 (include)
  CMakeLists.txt:201 (include)


-- Configuring incomplete, errors occurred!
See also "/home/SENSETIME/chenchang1/code/SuperPoint_SLAM/Thirdparty/pytorch/build/CMakeFiles/CMakeOutput.log".
See also "/home/SENSETIME/chenchang1/code/SuperPoint_SLAM/Thirdparty/pytorch/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "../tools/build_libtorch.py", line 30, in <module>
    subprocess.check_call(command, universal_newlines=True, env=my_env)
  File "/home/SENSETIME/chenchang1/miniconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/SENSETIME/chenchang1/code/SuperPoint_SLAM/Thirdparty/pytorch/tools/build_pytorch_libs.sh', '--use-cuda', '--use-nnpack', '--use-mkldnn', '--use-qnnpack', 'caffe2']' returned non-zero exit status 1.
为我的电脑安装了cuda9,但是gcc因为其他软件升级到了7.4.0版本，这个软件能否不使用cuda进行编译？
后面的你的superpoint-SLAM是否能够运行。

**Comment by KinglittleQ** [comment]
@cumtchenchang It's OK if not build with cuda.

**Comment by cumtchenchang** [comment]
你好 我现在也在杭州，能够加个微信吗，相互学习一下。我的微信 1820 520 5900。感谢

**Comment by liubamboo** [comment]
@cumtchenchang 你好，我也遇到了这个问题，请问你解决了吗？
