### ISSUE TITLE
Meaning of Dimension in The README

### ISSUE THREAD

**Issue by HyHuang1995** [KinglittleQ/SuperPoint_SLAM#3]
First, thanks for the great work!

I am just curious about the meaning of [Dimension](https://github.com/KinglittleQ/SuperPoint_SLAM/blob/0c6d22874c124449ce181b311bc89ac8b5c9bb12/README.md#L129).
Does it refer to the resolution of input images? If so, are there any criteria to adjust it for different sequences?

**Comment by KinglittleQ** [comment]
"Dimension" means the "size" of the trajectory. Specifically, [200, 300] means the maximum x and y does not exceed 200m and 300m respectively.

**Comment by HyHuang1995** [comment]
Thanks a lot!
