### ISSUE TITLE
用cpu来跑速度太慢，用gpu运行异常

### ISSUE THREAD

**Issue by stihuangyuan** [KinglittleQ/SuperPoint_SLAM#6]
你好，SPDetector网络如果用cpu来跑，整个前端速度1-2fps，感觉太慢
如果   detector.detect(mvImagePyramid[level], true)  用gpu来跑会出现异常
```
is cuda avaliable: 1
terminate called after throwing an instance of 'c10::Error'
  what():  grid_sampler(): expected input and grid to be on same device, but input is on cuda:0 and grid is on cpu (grid_sampler at /home/huangyuan/ml_ws/SuperPoint_SLAM-master/Thirdparty/pytorch/aten/src/ATen/native/GridSampler.cpp:576)
```
请问有什么好的解决方法吗？

**Comment by KinglittleQ** [comment]
Set to be true [here](https://github.com/KinglittleQ/SuperPoint_SLAM/blob/0c6d22874c124449ce181b311bc89ac8b5c9bb12/src/SPextractor.cc#L421).

**Comment by yuyadanyadan** [comment]
@stihuangyuan 你好 你编译libtorch库的时候 没有gpu能编译成功吗, 下半天也下不下来, 如果电脑没有gpu? 这整个工程能用不?

**Comment by KinglittleQ** [comment]
@yuyadanyadan 
可以的。
-----------
It's OK.

**Comment by stihuangyuan** [comment]
@KinglittleQ 恩，是把这个标志位置true。但是computeDescriptors这个函数会出现运行异常，grid_sampler好像需要输入数据是放在cpu上的。

**Comment by KinglittleQ** [comment]
@stihuangyuan 
试一下在[这里](https://github.com/KinglittleQ/SuperPoint_SLAM/blob/5d4dff48a0ea7e277fa83a077a139a689331825b/src/SuperPoint.cc#L133)之前添加 `grid = grid.to(torch::kCUDA);`
Add `grid = grid.to(torch::kCUDA);` before [here](https://github.com/KinglittleQ/SuperPoint_SLAM/blob/5d4dff48a0ea7e277fa83a077a139a689331825b/src/SuperPoint.cc#L133).

**Comment by bxh1** [comment]
> @stihuangyuan
> 试一下在[这里](https://github.com/KinglittleQ/SuperPoint_SLAM/blob/5d4dff48a0ea7e277fa83a077a139a689331825b/src/SuperPoint.cc#L133)之前添加 `grid = grid.to(torch::kCUDA);`
> Add `grid = grid.to(torch::kCUDA);` before [here](https://github.com/KinglittleQ/SuperPoint_SLAM/blob/5d4dff48a0ea7e277fa83a077a139a689331825b/src/SuperPoint.cc#L133).

还是不行

**Comment by bxh1** [comment]
> @stihuangyuan
> 试一下在[这里](https://github.com/KinglittleQ/SuperPoint_SLAM/blob/5d4dff48a0ea7e277fa83a077a139a689331825b/src/SuperPoint.cc#L133)之前添加 `grid = grid.to(torch::kCUDA);`
> Add `grid = grid.to(torch::kCUDA);` before [here](https://github.com/KinglittleQ/SuperPoint_SLAM/blob/5d4dff48a0ea7e277fa83a077a139a689331825b/src/SuperPoint.cc#L133).

应该在这个函数里加
SPDetector::computeDescriptors(const std::vector<cv::KeyPoint> &keypoints, cv::Mat &descriptors)
{
