### ISSUE TITLE
buildSystem(): NaN within Jacobian for edge 0x55c55a100100 for vertex 0

### ISSUE THREAD

**Issue by Luxcy** [KinglittleQ/SuperPoint_SLAM#8]
I follow what you said. 
But I have an error with it.
Like, follow.
`
Examples/Monocular/mono_kitti ./Vocabulary/superpoint_voc.yml.gz ./Examples/Monocular/KITTI04-12.yaml  ~/dataset/kitti_odo/odometry_gray/sequences/05
Creating orb-slam system ...
ORB-SLAM2 Copyright (C) 2014-2016 Raul Mur-Artal, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: Monocular

Loading ORB Vocabulary. This could take a while...

Camera Parameters: 
- fx: 707.091
- fy: 707.091
- cx: 601.887
- cy: 183.11
- k1: 0
- k2: 0
- p1: 0
- p2: 0
- fps: 10
- color order: RGB (ignored if grayscale)

ORB Extractor Parameters: 
- Number of Features: 2000
- Scale Levels: 4
- Scale Factor: 1.2
- Initial Fast Threshold: 0.015
- Minimum Fast Threshold: 0.007

-------
Start processing sequence ...
Images in the sequence: 2761

4001
desc size: 4001 256
mvKeys.size(): 4001
4000
desc size: 4000 256
mvKeys.size(): 4000
start to intialize...
3166
desc size: 3166 256
mvKeys.size(): 3166
start to intialize...
intializing...
New Map created with 298 points
buildSystem(): NaN within Jacobian for edge 0x55c55a2b21c0 for vertex 1
buildSystem(): NaN within Jacobian for edge 0x55c55a100100 for vertex 0`

Can it run good on your computer? Thank you very much!

**Comment by KinglittleQ** [comment]
I've never met such a problem. Would other sequences cause the same problem?

**Comment by Luxcy** [comment]
I find the answer in https://github.com/raulmur/ORB_SLAM2/issues/341.
Now it can run.

**Comment by Luxcy** [comment]
I have another question.
I run it very slowly. Because of the CPU?
I resize my images by 0.5 scales.

**Comment by KinglittleQ** [comment]
You can enable GPU by set `cuda=true` at this [line](https://github.com/KinglittleQ/SuperPoint_SLAM/blob/5d4dff48a0ea7e277fa83a077a139a689331825b/src/SPextractor.cc#L421):
``` cpp
        detector.detect(mvImagePyramid[level], true);
```
