### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by shylockyuan** [KinglittleQ/SuperPoint_SLAM#9]
Hello! Thanks for your code!
    When I installed Librotch with the code:
    git clone --recursive -b v1.0.1 https://github.com/pytorch/pytorch
    cd pytorch && mkdir build && cd build
    python ../tools/build_libtorch.py
    Some errors occured:
wu@wu:~/pytorch/build$ python ../tools/build_libtorch.py
Traceback (most recent call last):
  File "../tools/build_libtorch.py", line 30, in <module>
    subprocess.check_call(command, universal_newlines=True, env=my_env)
  File "/home/wu/anaconda3/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/wu/anaconda3/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/wu/anaconda3/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/home/wu/anaconda3/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

I don't know how to solve it. Could you give me some advice? Thanks a lot!

**Comment by KinglittleQ** [comment]
It seems like the building script don't have permission right. Did you try to add `sudo` before your build command?
``` shell
sudo python ../tools/build_libtorch.py
```

**Comment by shylockyuan** [comment]
yes, but it doesn't work. I download the pytorch in Windows with git clone --recursive -b v1.0.1 https://github.com/pytorch/pytorch  because I can't download it in linux. But it's strange in windows it is 1.14G while in linux is 360M.

**Comment by KinglittleQ** [comment]
1.14G is a normal size.

**Comment by shylockyuan** [comment]
Hello, when I build DBoW3, some errors occur:

/home/wu/SuperPoint_SLAM-master/Thirdparty/DBoW3/src/BowVector.cpp: At global scope:
/home/wu/SuperPoint_SLAM-master/Thirdparty/DBoW3/src/BowVector.cpp:153:1: error: ‘uint64_t’ does not name a type
 uint64_t BowVector::getSignature()const{
 ^
CMakeFiles/DBoW3.dir/build.make:62: recipe for target 'CMakeFiles/DBoW3.dir/src/BowVector.cpp.o' failed
make[2]: *** [CMakeFiles/DBoW3.dir/src/BowVector.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/DBoW3.dir/all' failed
make[1]: *** [CMakeFiles/DBoW3.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Do you know how to solve this problem? Thank you very much!

**Comment by shylockyuan** [comment]
hello , I can'd build DBOW3. The error is:
/home/wu/SuperPoint_SLAM-master/Thirdparty/DBoW3/src/Database.h:31:12: warning: ‘DBoW3::MIN_COMMON_WORDS’ defined but not used [-Wunused-variable]
 static int MIN_COMMON_WORDS = 5;
            ^
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/SuerPoint_SLAM.dir/all' failed
make[1]: *** [CMakeFiles/SuerPoint_SLAM.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I have no idea about this problem

**Comment by KinglittleQ** [comment]
https://stackoverflow.com/questions/11069108/uint32-t-does-not-name-a-type

**Comment by shylockyuan** [comment]
Sorry, I may not get your point. I try #include <stdint.h>, it doesn't work.
